name: Push-Images

on:
  release:
    types: [published]

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Image
        working-directory: ../../docker
        run: docker-compose build . 
    
      - name: Push Image
        working-directory: ../../docker
        run: docker-compose push . 
